### ISSUE TITLE
Constraining CL and not alpha

### ISSUE THREAD

**Issue by TranquilOctopus** [renoelmendorp/AVLWrapper#5]
Hi,

I'm not sure if this is an error or if it's user error, but attempting to set a case to take a CL argument rather than an alpha argument doesn't work and defaults to Alpha = 0 with no CL constrained.

I'm talking about attempting to run the following piece of code:

case = [Case(name='cruise', CL = 0.2)]
session = Session(geometry=geometry, cases=case)

But I'm not sure I'm using it properly. In AVL this is usually set through making alpha dependent on CL, through A -> C -> <insert value> but I'm not sure how it works here. Is this user error or is it a function that is NYI?

**Comment by renoelmendorp** [comment]
Hi,

As can been read in the AVL documentation, parameters which are calculated for a case are overwritten by analysis results. Since alpha defaults to 0, the CL is overwritten by the CL value which corresponds to an AoA of 0. To run an analysis at a certain CL, the alpha needs to be constrained by prescribing a CL. To do this with the wrapper:

cl_param = Parameter(name='alpha', constraint='CL', value=0.2)
cl_case = Case(name='Cruise CL', alpha=cl_param)

Hope this helps...

Reno
