### ISSUE TITLE
Adding VM File to session results

### ISSUE THREAD

**Issue by nberger8** [renoelmendorp/AVLWrapper#7]
I'm not sure if opening an issue is the correct way to address this, but is it possible for there to be an addition to AVLWrapper that adds the .vm file (strip shear,moment) that AVL is able to output to the session results dictionary? This data is incredibly useful when calculating shear load and moment distributions across a wing which I must do for a project I am working on, but unfortunately I am not experienced enough in FileIO to attempt this myself.

**Comment by renoelmendorp** [comment]
Since every AVL output file has a slightly different format, a reader function should be added to `output.py` for the vm file.
Creating this should be straightforward, but I don't have time to implement this right away; I can't make any promise when this will be added.

Pull requests are always welcome ;-)
