### ISSUE TITLE
['StripForces'] errors when wing is mirrored with span > 100 units

### ISSUE THREAD

**Issue by Dohn27** [renoelmendorp/AVLWrapper#9]
Hi,

It looks like if a wing half span is over 100 units long and is y duplicated, the strip forces on the mirrored side past Y=-100 will have incorrect Yle and Cl values. I haven't investigated too thoroughly, but it looks like the incorrect Yle values past -100 become chord lengths.

![bad_y_cl](https://user-images.githubusercontent.com/10335495/69559529-20dbf680-0f78-11ea-9b86-1bf533fd28d5.png)

It can be worked around by taking half of the results array, multiplying the Yle by -1, and stacking the two half arrays together.

![good_y_cl](https://user-images.githubusercontent.com/10335495/69559543-28030480-0f78-11ea-96c7-1458309e6e19.png)

I attached an example to help reproduce the error.
[avlwrapper_debug.py.zip](https://github.com/renoelmendorp/AVLWrapper/files/3887653/avlwrapper_debug.py.zip)

**Comment by renoelmendorp** [comment]
This is an issue with the AVL program itself, which cannot be solved in the wrapper.
Looking at the output files of AVL, you can see the following:
```
65 -95.0000  18.3333  61.1112   3.4235
66 -98.3333  17.2222  57.4073   3.2395
67 ********  16.1111  53.7038   3.0432
68 ********  15.0000  49.9999   2.8300
69 ********  13.8889  46.2963   2.5909
70 ********  12.7778  42.5925   2.3076
71 ********  11.6667  38.8889   1.9385
72 ********  10.5556  35.1852   1.3707
```
Values with more than 3 characters before the decimal sign (including the '-') will be replaced by ****.
Since AVL is potential flow, you could try to scale your problem down, results should be easy to scale up again.

**Comment by renoelmendorp** [comment]
Warning is now raised and table formatting is fixed when this problem arises.
